### ISSUE TITLE
🚀 Feature: Captcha verification

### ISSUE THREAD

**Issue by Meldiron** [Basharath/FormEasy#1]
To prevent spamming, some contact forms implement human verification tools such as [reCAPTCHA v2](https://developers.google.com/recaptcha/docs/display), [hCaptcha](https://www.hcaptcha.com/), and others.

I am proposing a feature in FormEasy to allow communication with these captcha servers to validate form submissions.

One way of implementing it I can see is to update `FormEasy.action(req);` function with new options parameter:

```js
const options = {
  captcha: "recaptcha_v2",
  captchaConfig: { secretKey: "........." }
};

FormEasy.action(req, options);
```

FormEasy would then look for proper implementation of specific captcha on a website.. That can be verified by looking at JSON data, and for instance, looking for `g-recaptcha-response` key in the case of Recaptcha V2.

Finally FormEasy talks to API servers to verify the token from captcha.

(all of that properly documented, of course)

Would you be interested in this feature inside FormEasy? I would love to contribute to this feature in my free time.

**Comment by Basharath** [comment]
Hi [Meldiron](https://github.com/Meldiron),

So glad to see the first contribution request :)

Having a spam filter while submitting these forms is a great idea. 
Please add whatever you think is relevant to implement this feature. 

For testing it you can do it directly inside the `doPost` function while using this library and once it works fine include that code in main `Code.js` file of this library and make a pull request and I'll verify the same from my end and then make a new version to this library with this feature.

Thank you for taking the time to contact and feel free to make your contributions to make this useful for all. 

See you!

**Comment by Basharath** [comment]
Captcha validation is available through FormEasy version 2.
