### ISSUE TITLE
Spreadsheet sort data by date/time

### ISSUE THREAD

**Issue by coldes** [Basharath/FormEasy#3]
Request: would be good on a Form Submission, the spreadsheet auto sorts [by date/time] so latest is top row (2)  - thank you

**Comment by Basharath** [comment]
Hey, 

Thanks for the suggestion. It's going to be a very useful feature. 
I'll add it in the next version of this library.

**Comment by Basharath** [comment]
With version 2, all the form submissions will be logged on top rows sorted by date. 

Please select Version 2(or latest) while using the FormEasy library for new features.
