### ISSUE TITLE
works in postman but not in my html site

### ISSUE THREAD

**Issue by vissenisgezond** [Basharath/FormEasy#5]
[my site](https://vissenisgezond.github.io/detekstbeer/)

on my site if i send the form the text fields values are not send only the headers

![image](https://github.com/Basharath/FormEasy/assets/88384231/b4dd6f28-e42f-42cf-9732-e09ce942626d)

`<div class="form-container">
								<form action="https://script.google.com/macros/s/AKfycbzrq4fNAtdprIhWNuG9jKUZWhQzvJs6vBU4RvbFlvQY8yYGmWJapgjEg8F3cyyzgJzp/dev" method="POST" class="cf">
									<div class="form-field">
										<input type="text" name="name" id="input-name" placeholder="Naam" required>
									</div>
									<div class="form-field">
										<input type="email" name="email" id="input-email" placeholder="Emailadres" required>
									</div>
									<div class="form-field">
										<input type="text" name="subject" id="input-subject" placeholder="Onderwerp" required>
									</div>
									<div class="form-field">
										<textarea name="message" id="input-message" placeholder="Bericht" required></textarea>
									</div>
									<div class="form-field button-group">
										<input type="submit" value="Verstuur" id="input-submit">
										<a href="https://wa.me/639614391029" class="whatsapp-btn">
											<i class="fab fa-whatsapp"></i> +63 961 439 10299
										</a>
									</div>
								</form>`

"function doPost(req) {
  Logger.log(req);
  FormEasy.setSheet('haha'); // Optional, replace with the name of the sheet you want to use
  FormEasy.setEmail('youremail@domain.com'); // Replace with your email if you want to receive email notifications
  FormEasy.setSubject('New form submission'); // Optional, this will be the subject of the email notification
  FormEasy.setFormHeading('Form Submission Details'); // Optional, this will be the heading in the email notification
  FormEasy.setFields('name', 'email', 'subject', 'message' , 'message'); // Replace these with the names of the fields in your form
  return FormEasy.action(req); // This should be at the end and return it
}
" Could some one point me in the right direction?

**Comment by jireh-sg-leo** [comment]
You are not alone. What I found is if I just post FormData, I get nothing in the spreadsheet. This is what I came up with after a bit of fiddling. Basically, need to transform the entries in FormData to a JSON dict.

```html
<script>
   const form = document.querySelector("#form")
   const submitButton = document.querySelector("#submit")
   const scriptURL = 'https://script.google.com/macros/s/<Deployment ID>/exec'
   
   form.addEventListener('submit', e => {
     submitButton.disabled = true;
     e.preventDefault();
     let requestBody = new FormData(form);
   
     var object = {};
     requestBody.forEach((value, key) => object[key] = value);
      var json = JSON.stringify(object);
   
     fetch(scriptURL,
        { method: 'POST',
          headers: {
            'Content-Type': 'text/plain;charset=utf-8',
          },     
          body: json
        })
       .then(response => {
          alert('Success!', response.json());
          submitButton.disabled = false;
         })
       .catch(error => {
       alert('Error!', error.message);
         submitButton.disabled = false;
   
       }
       )
   })
</script>
```

**Comment by Basharath** [comment]
> [my site](https://vissenisgezond.github.io/detekstbeer/)
> 
> on my site if i send the form the text fields values are not send only the headers
> 
> ![image](https://user-images.githubusercontent.com/88384231/247827450-b4dd6f28-e42f-42cf-9732-e09ce942626d.png)
> 
> `<div class="form-container"> <form action="https://script.google.com/macros/s/AKfycbzrq4fNAtdprIhWNuG9jKUZWhQzvJs6vBU4RvbFlvQY8yYGmWJapgjEg8F3cyyzgJzp/dev" method="POST" class="cf"> <div class="form-field"> <input type="text" name="name" id="input-name" placeholder="Naam" required> </div> <div class="form-field"> <input type="email" name="email" id="input-email" placeholder="Emailadres" required> </div> <div class="form-field"> <input type="text" name="subject" id="input-subject" placeholder="Onderwerp" required> </div> <div class="form-field"> <textarea name="message" id="input-message" placeholder="Bericht" required></textarea> </div> <div class="form-field button-group"> <input type="submit" value="Verstuur" id="input-submit"> <a href="https://wa.me/639614391029" class="whatsapp-btn"> <i class="fab fa-whatsapp"></i> +63 961 439 10299 </a> </div> </form>`
> 
> "function doPost(req) { Logger.log(req); FormEasy.setSheet('haha'); // Optional, replace with the name of the sheet you want to use FormEasy.setEmail('[youremail@domain.com](mailto:youremail@domain.com)'); // Replace with your email if you want to receive email notifications FormEasy.setSubject('New form submission'); // Optional, this will be the subject of the email notification FormEasy.setFormHeading('Form Submission Details'); // Optional, this will be the heading in the email notification FormEasy.setFields('name', 'email', 'subject', 'message' , 'message'); // Replace these with the names of the fields in your form return FormEasy.action(req); // This should be at the end and return it } " Could some one point me in the right direction?

So basically, you are trying to make `POST` request directly. Because `Content-Type` will be different there might be a problem.

Please follow this one to get worked: https://github.com/Basharath/FormEasy#form-submission-using-fetch

**Comment by Basharath** [comment]
> You are not alone. What I found is if I just post FormData, I get nothing in the spreadsheet. This is what I came up with after a bit of fiddling. Basically, need to transform the entries in FormData to a JSON dict.
> 
> ```
> <script>
>    const form = document.querySelector("#form")
>    const submitButton = document.querySelector("#submit")
>    const scriptURL = 'https://script.google.com/macros/s/<Deployment ID>/exec'
>    
>    form.addEventListener('submit', e => {
>      submitButton.disabled = true;
>      e.preventDefault();
>      let requestBody = new FormData(form);
>    
>      var object = {};
>      requestBody.forEach((value, key) => object[key] = value);
>       var json = JSON.stringify(object);
>    
>      fetch(scriptURL,
>         { method: 'POST',
>           headers: {
>             'Content-Type': 'text/plain;charset=utf-8',
>           },     
>           body: json
>         })
>        .then(response => {
>           alert('Success!', response.json());
>           submitButton.disabled = false;
>          })
>        .catch(error => {
>        alert('Error!', error.message);
>          submitButton.disabled = false;
>    
>        }
>        )
>    })
> </script>
> ```

Yeah this is the working solution. A sample submission code is put in the README already. https://github.com/Basharath/FormEasy#form-submission-using-fetch
