### ISSUE TITLE
Email and subject not working

### ISSUE THREAD

**Issue by TFM110** [Basharath/FormEasy#7]
I setup everything but I don't get the email notifications and I also don't get the subjects. What did I do wrong?

![image](https://github.com/Basharath/FormEasy/assets/43244309/2d4fa080-850a-452b-b531-62033b2e1d56)
![image](https://github.com/Basharath/FormEasy/assets/43244309/631ce659-9f52-4b29-a12c-4b0ab164b018)
![image](https://github.com/Basharath/FormEasy/assets/43244309/ca519862-94cd-4c38-8d89-ad51e30ad815)
![image](https://github.com/Basharath/FormEasy/assets/43244309/b0a2e0c3-279d-46f4-96e0-df85cb98297e)
![image](https://github.com/Basharath/FormEasy/assets/43244309/0ca35b62-d763-4f13-8cf8-694336f80b58)

**Comment by Basharath** [comment]
Are you able to submit the form? If yes, then did you redeploy the script, if not then your changes are not reflected.

**Comment by TFM110** [comment]
Yes I am able to submit the form and I have already redeployed
https://github.com/Basharath/FormEasy/assets/43244309/84b8a073-dd4a-45f9-b1c0-1e1db0428ee3

**Comment by TFM110** [comment]
> Are you able to submit the form? If yes, then did you redeploy the script, if not then your changes are not reflected. 

Yes I'm able to submit and I have redeployed but it's still broken.

**Comment by Basharath** [comment]
Try changing the `subject` keyword to some other, as the subject has a defined method for setting it. 

Also check the data that you get from the form before submitting it, most probably it should solve.

**Comment by TFM110** [comment]
Sorry, I'm confused what you asked me to do. Where do you want me to change the keyword? And how do you want me to check my inputs?

**Comment by Basharath** [comment]
Do one thing, try to submit some random data using JavaScript, like shown here: [https://github.com/Basharath/FormEasy#form-submission-using-fetch](https://github.com/Basharath/FormEasy#form-submission-using-fetch)

This will give you an idea if things are working fine. 

`FormEasy.setFields('name', 'email', 'subject', 'message')` remove `subject` input here and try using some other keyword.

**Comment by TFM110** [comment]
Didn't work

![image](https://github.com/Basharath/FormEasy/assets/43244309/1aa54049-b8f1-4d23-91dc-b0ac948a7402)
![image](https://github.com/Basharath/FormEasy/assets/43244309/2d95a67d-9335-40fc-8a5a-ef7ba8c8295d)
![image](https://github.com/Basharath/FormEasy/assets/43244309/8b297860-6ac1-4b96-8936-a8e139227e9d)

**Comment by Basharath** [comment]
Why are you using `FormData` you could simply use the data object declared and directly write the fetch function. 
Like this [https://github.com/Basharath/FormEasy#form-submission-using-fetch](https://github.com/Basharath/FormEasy#form-submission-using-fetch)

Try it in the simplest way. There's no way it doesn't work. Try creating a new Google sheet and repeat exactly as shown in the demo video.

**Comment by TFM110** [comment]
I using FormDats cause that's what is used in your demo code
https://stackblitz.com/edit/js-55dzc8?file=index.html,index.js

**Comment by TFM110** [comment]
Can you just look at my codes and write me what I should have? I don't use JS, I don't understand it. I only am using JS for this. I am not a programmer

**Comment by ali2kan** [comment]
There is nothing wrong with FormEasy, it works nicely. Just follow [The Instructions](https://devapt.com/formeasy#instructions) , or follow along with the demo video. Once you get it working in the most simple way possible, then start adapting developing it to fit your situation. 

If you are still stuck, it might be a small error, try using ChatGPT or some of the LLM to read your code and guide you though fixing it. 

Best of luck to you!

**Comment by TFM110** [comment]
> There is nothing wrong with FormEasy, it works nicely. Just follow [The Instructions](https://devapt.com/formeasy#instructions) , or follow along with the demo video. Once you get it working in the most simple way possible, then start adapting developing it to fit your situation. 
> 
> If you are still stuck, it might be a small error, try using ChatGPT or some of the LLM to read your code and guide you though fixing it. 
> 
> Best of luck to you!  

That doesn't help with my issue but thanks. Next time, please look at my screenshots and what I should change. Again, I'm not a programmer. The video didn't even show how you can code the contact form into a website.

**Comment by Basharath** [comment]
I think the problem is with your Google sheets setup. 

Try replicating as it is shown in this [FormEasy video](https://www.youtube.com/watch?v=0u75mtnhifM/)

Can also go through this [FormEasy article](https://devapt.com/formspree-alternative-formeasy)

Hopefully, the above resources should help you with all.

**Comment by TFM110** [comment]
Do I need to fill out for the js script
```
const data = {
  name: 'John',
  email: 'john@domain.com',
  message: 'Receiving forms is easy and simple now!',
};
```

or can i just use
```
const url = 'https://script.google.com/macros/s/<Deployment ID>/exec';

fetch(url, {
  method: 'POST',
  headers: {
    'Content-Type': 'text/plain;charset=utf-8',
  },
  body: JSON.stringify(data),
})
  .then((res) => res.json())
  .then((data) => console.log('data', data))
  .catch((err) => console.log('err', err));
```
  
Also, I want to be able to get a subject line, so what should i have? will this work?

```
function doPost(req) {
  FormEasy.setEmail('tauseef.afraz.1@gmail.com'); // To receive email notification(optional)
  FormEasy.setSheet('Contact Form'); // Optional
  FormEasy.setFields('name', 'email', 'subject', 'message'); // Optional(name, email, messsage are default)
  return FormEasy.action(req); // Mandatory to return action method
}
```

**Comment by TFM110** [comment]
I fixed everything but I am still not getting the subject line

**Comment by TFM110** [comment]
Fixed
I remade the entire spreadsheet and it worked
![image](https://github.com/Basharath/FormEasy/assets/43244309/3f060501-ce1c-4794-936e-db5c059d07e4)
![image](https://github.com/Basharath/FormEasy/assets/43244309/bf6077e2-5c0c-4edd-923f-b3a1e998ec3e)
![image](https://github.com/Basharath/FormEasy/assets/43244309/3a7baef8-1b07-44c8-a506-8f3412aae48a)

**Comment by Basharath** [comment]
That's the thing, there was a problem with the sheet itself. 

Great you solved it. Happy form collection!
